# Generated by Django 4.2.11 on 2025-03-19 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_verified_user_joined_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='joined_date',
        ),
    ]
